### ISSUE TITLE
Importing local relative paths does not work

### ISSUE THREAD

**Issue by djacu** [Mic92/pythonix#18]
I am trying to use pythonix to import some local files and run some unit tests. However, it doesn't seem to parse relative paths properly. All of these methods work in the Nix REPL.

```python
>>>import nix

>>> nix.eval('with import ./math.nix; isEven 2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
nix.NixError: not an absolute path: '././math.nix'

>>> nix.eval('with import (./. + "math.nix"); isEven 2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
nix.NixError: not an absolute path: '././.'

>>> nix.eval('with import (builtins.toString ./math.nix); isEven 2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
nix.NixError: not an absolute path: '././math.nix'
```

**Comment by Mic92** [comment]
I am not really using this project anymore and it would require some porting changes to newer nix apis.
You can also use the `nix eval --json --expr` to get json output from nix and use the python json library to parse it again.
This is how I actually end up doing it in all my python projects. https://github.com/Mic92/nix-update/blob/3143af043d4324ee4c6a91ff7294c5c34fe459b6/nix_update/eval.py#L77
